services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull llama3.2:3b && wait"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: medical-match-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_ANONYMIZED_TELEMETRY=False
      - ANONYMIZED_TELEMETRY=False
      
    volumes:
      - chroma_data:/app/data
      - ./reports:/app/reports
      - ./model_cache:/root/.cache/chroma/onnx_models
    depends_on:
      - ollama

volumes:
  ollama_data:
  chroma_data:
